CREATE TABLE Class
(
	Code NVARCHAR(4) NOT NULL,
	HeadId INT NOT NULL,

	CONSTRAINT PK_Class PRIMARY KEY (Code),
	CONSTRAINT FK_Class_Teacher FOREIGN KEY (HeadId) REFERENCES Teacher(Id),
	CONSTRAINT UC_Class UNIQUE (HeadId)
)
