CREATE TABLE Pupil
(
	Id INT IDENTITY(1,1) NOT NULL,
	Lastname NVARCHAR(40) NOT NULL,
	Firstname NVARCHAR(40) NOT NULL,
	ClassCode NVARCHAR(4) NOT NULL,
	IsStudy BIT NOT NULL DEFAULT 1,

	CONSTRAINT PK_Pupil PRIMARY KEY (Id),
	CONSTRAINT FK_Pupil_Class FOREIGN KEY (ClassCode) REFERENCES Class(Code)
)

